# Generated by Django 3.2.7 on 2021-11-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uva_guide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('student', 'Student'), ('organizer', 'Organizer')], default='student', max_length=255),
        ),
    ]
