# Generated by Django 3.2.7 on 2021-11-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uva_guide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='org',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
