# Generated by Django 3.2.7 on 2021-11-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uva_guide', '0002_auto_20211107_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
