# Generated by Django 3.2.7 on 2021-11-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uva_guide', '0002_profile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firstTime',
            field=models.BooleanField(default=True),
        ),
    ]
