# Generated by Django 3.2.7 on 2021-11-08 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uva_guide', '0003_alter_event_location'),
        ('uva_guide', '0003_profile_firsttime'),
    ]

    operations = [
    ]
